Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false
  # IgnorePatterns:
  # - ('|").*('|") # just strings!

Metrics/MethodLength:
  Max: 11 # TODO: remove; default 10